---
# GitHub Pages defaults
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

# GitHub Pages enforced
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false

timezone: Europe/London

exclude:
  - CNAME
  - CODE_OF_CONDUCT.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
