#!/bin/sh
branch="$(git name-rev --name-only HEAD)"
git add -A
git stash
git branch -D master 2> /dev/null
git checkout --orphan master
git reset
jekyll build
git add -f _site
git commit -m "Temporary _site commit"
rm .gitignore
git add -A
git reset --hard
mv _site/* .
rmdir _site
git add -A
git commit --amend -m "Generate site"
git checkout "$branch"
git stash pop
git push -f origin master
